export const TODOS_LOADED = 'TODOS_LOADED';
export const TODO_ADDED = 'TODO_ADDED';
export const TODO_STATE_TOGGLED = 'TODO_STATE_TOGGLED';

export const TEXT_FILTER_CHANGED = 'TEXT_FILTER_CHANGED';
export const STARRED_FILTER_TOGGLED = 'STARRED_FILTER_TOGGLED';
